# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/Rails
    branches:
          only:
            - develop
    docker:
      - image: circleci/ruby:2.3.1-node-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PG_HOST: localhost

    parallelism: 1

    steps:
      - checkout
      - run: COVERAGE=true bundle exec rake rspec



